#
# @copiryght = 2024 SilverCore
# @autor = Silverdium
# @autor = MisterPapaye
#

on load:
    send "Loading config with ./plugins/skript/scripts/blacklist.sk" to console

command /blacklist [<text>] [<player>]:
    aliases: bl
    permission: skript.staff.blacklist
    permission message: %{permmessage}%
    trigger:
        if arg-1 is set:
            if arg-1 is "reset":
                set {blacklist::*} to ""
                send "%{prefix::cheat}% La blacklist a bien été réinitialiser" to player
                send "%{prefix::cheat}% BlackList : %{blacklist::*}%" to player
            if arg-1 is "add":
                if arg-2 is set:
                    add arg-2 to {blacklist::*}
                    send "%{prefix::cheat}% %arg-2% a bien été ajouter dans la blacklist" to player
                    send "%{prefix::cheat}% %{blacklist::*}%" to player
                else:
                    send "%{prefix::cheat}% &cUsage : /blacklist <target: add, reset, delete, show> <player>" to player
            if arg-1 is "delete":
                if arg-2 is set:
                    remove arg-2 from {blacklist::*}
                    send "%{prefix::cheat}% %{arg-2}% a bien été retirer dans la blacklist" to player
                    send "%{prefix::cheat}% %{blacklist::*}%" to player
                else:
                    send "%{prefix::cheat}% &cUsage : /blacklist <target: add, reset, delete, show> <player>" to player
            if arg-1 is "show":
                send "%{prefix::cheat}% %{blacklist::*}%" to player
        else:
            send "%{prefix::cheat}% &cUsage : /blacklist <target: add, reset, delete, show> <player>" to player

#end