#
# @copyright = 2024 SilverCore
# @author = Silverdium
# @author = MisterPapaye
#

options:
    tab-header: "&6Bienvenue sur le serveur!%nl%"
    tab-footer: "&7Jouez et amusez-vous!%nl%"

on load:
    send "&a[TabManager] Chargement de la configuration depuis ./plugins/skript/scripts/tab.sk" to console

on join:
    set tab list header of player to "{@tab-header}" to player
    set tab list footer of player to "{@tab-footer}" to player

#end